// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TracePointApi.Data;

#nullable disable

namespace TracePointAPI.Migrations
{
    [DbContext(typeof(TracePointDbContext))]
    partial class TracePointDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("TracePointApi.Models.Case", b =>
                {
                    b.Property<int>("CaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CaseId");

                    b.ToTable("Cases");

                    b.HasData(
                        new
                        {
                            CaseId = 1,
                            CaseName = "The Missing Prototype",
                            Description = "A technology company has reported that an experimental prototype disappeared from its research laboratory between 22:00 and 00:00.",
                            Status = "Open"
                        });
                });

            modelBuilder.Entity("TracePointApi.Models.Evidence", b =>
                {
                    b.Property<int>("EvidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EvidenceId");

                    b.ToTable("Evidence");

                    b.HasData(
                        new
                        {
                            EvidenceId = 1,
                            Description = "Jamie Smith's access card was used to enter the research laboratory at 23:41.",
                            Location = "Security Office",
                            Title = "Security Access Log"
                        },
                        new
                        {
                            EvidenceId = 2,
                            Description = "CCTV footage shows a person entering the laboratory at approximately 23:43. The person's face cannot be clearly identified.",
                            Location = "Research Laboratory",
                            Title = "CCTV Report"
                        },
                        new
                        {
                            EvidenceId = 3,
                            Description = "A partial fingerprint was found on the prototype storage cabinet. The fingerprint belongs to a person who regularly works in the laboratory.",
                            Location = "Research Laboratory",
                            Title = "Fingerprint Report"
                        },
                        new
                        {
                            EvidenceId = 4,
                            Description = "An email sent shortly before the incident states: \"The prototype must be moved before tomorrow's demonstration.\"",
                            Location = "Archive Room",
                            Title = "Email Message"
                        },
                        new
                        {
                            EvidenceId = 5,
                            Description = "A photograph taken after the incident shows that the prototype cabinet was open and the laboratory lights were switched off.",
                            Location = "Research Laboratory",
                            Title = "Photograph"
                        });
                });

            modelBuilder.Entity("TracePointApi.Models.Investigation", b =>
                {
                    b.Property<int>("InvestigationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateStarted")
                        .HasColumnType("TEXT");

                    b.Property<int>("SuspectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InvestigationId");

                    b.ToTable("Investigations");
                });

            modelBuilder.Entity("TracePointApi.Models.Suspect", b =>
                {
                    b.Property<int>("SuspectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SuspectId");

                    b.ToTable("Suspects");

                    b.HasData(
                        new
                        {
                            SuspectId = 1,
                            Description = "Alex developed the software used by the prototype and had access to the laboratory.",
                            Name = "Alex Morgan",
                            Occupation = "Software Developer"
                        },
                        new
                        {
                            SuspectId = 2,
                            Description = "Jamie was responsible for security at the building on the night of the incident.",
                            Name = "Jamie Smith",
                            Occupation = "Security Officer"
                        },
                        new
                        {
                            SuspectId = 3,
                            Description = "Taylor worked with the research team and had access to the laboratory during working hours.",
                            Name = "Taylor Williams",
                            Occupation = "Research Assistant"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
